name: Continuous Integration GoFrame

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.25'
      
    - name: Download Go modules
      run: go mod tidy

    - name: Test
      run: go test -v ./...
  
